services:
  postgres:
    image: postgres:17.5
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    hostname: postgres
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_EXPOSE_PORT}:5432"
    volumes:
      - "/data/api-gateway/db:${DATABASE_STORE}"
    restart: always
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    hostname: backend
    environment:
      LOG_PATH: ${LOG_PATH}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_DEFAULT_SCHEMA: ${DATABASE_DEFAULT_SCHEMA}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    ports:
      - "${BACKEND_EXPOSE_PORT:-8080}:8080"
    volumes:
      - "/data/api-gateway/log:${LOG_PATH}"
    restart: always
    networks:
      - backend

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: ${COMPOSE_PROJECT_NAME}-gateway
    hostname: gateway
    environment:
      BACKEND_SERVICE_URL: http://backend:8080
    depends_on:
      - backend
    ports:
      - "${GATEWAY_EXPOSE_PORT:-9090}:9090"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
