version: '3.9'

services:
  postgres:
    image: postgres:17.5
    container_name: ${COMPOSE_PROJECT_NAME}-postgres-dev
    hostname: postgres
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_EXPOSE_PORT}:5432"
    volumes:
      # 左边是宿主机路径，你要改成你的真实路径
      - "D:/docker/store/api-gateway/db:${DATABASE_STORE}"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge