version: '3.9'

services:
  postgres:
    image: postgres:17.5
    container_name: ${COMPOSE_PROJECT_NAME}-postgres-dev
    hostname: postgres
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_EXPOSE_PORT}:5432"
    volumes:
      - "D:/docker/store/api-gateway/db:${DATABASE_STORE}"
    restart: always
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis-dev
    hostname: redis
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_EXPOSE_PORT}:6379"
    volumes:
      - "D:/docker/store/api-gateway/redis:${REDIS_STORE}"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge